# Generated by Django 4.0.5 on 2022-07-19 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('experienceInYears', models.IntegerField(default=0)),
                ('rating', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
                ('image', models.ImageField(null=True, upload_to='property/%Y/%m/%d/')),
                ('created', models.DateField(auto_now=True)),
                ('updated', models.DateField(auto_now=True)),
            ],
        ),
    ]
