# Generated by Django 4.0.5 on 2022-07-19 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('shortDescription', models.CharField(max_length=255)),
                ('longDescription', models.TextField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('featured', models.BooleanField(default=True)),
                ('status', models.CharField(max_length=255)),
                ('kitchen', models.IntegerField(default=0)),
                ('hall', models.IntegerField(default=0)),
                ('bedroom', models.IntegerField(default=0)),
                ('roadInFront', models.CharField(max_length=255)),
                ('distanceFromHighway', models.IntegerField(default=0)),
                ('garage', models.BooleanField(default=False)),
                ('shutter', models.BooleanField(default=False)),
                ('coverImage', models.ImageField(null=True, upload_to='property/%Y/%m/%d/')),
                ('cardImage', models.ImageField(null=True, upload_to='property/%Y/%m/%d/')),
                ('area', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('created', models.DateField(auto_now=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agent.agent')),
            ],
        ),
    ]
